### ISSUE TITLE
GitHub Link is broken

### ISSUE THREAD

**Issue by pqt** [sell/personal-website#1]
Hey! Stumbled upon your site, noticed your GitHub link has an extra slash in it, just wanted to let you know :)

https://github.com/sell/personal-website/blob/master/src/includes/main.pug#L24

```diff
- https://github./com/sell
+ https://github.com/sell
```

**Comment by sell** [comment]
Sorry for late reply, thanks for this appreciate it, will fix been real busy with my projects.

Kind of amazed to have someone like you report a issue!
